Revised special member funcs; miscellanea.
Rule: #include <functional> instead of <memory> for std::reference_wrapper (duh).
Error, *MetaField, Record, Column, IDGenerator, Serializer, Driver: deleted copy op & ctor; defaulted move complements.
Error: std::move(msg) in value ctor; doc uniformity in move ctor.
Metadata: doc uniformity in value ctor.